version: "3.0"
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - 9200:9200
  kibana:
    container_name: kb-container
    # image: docker.elastic.co/kibana/kibana:8.8.2
    image: repo.vectoredge.io/vekibana:v1
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
  elastaalert:
    container_name: elastalert
    image: jertel/elastalert2:2.12.0
    environment:
      - ELASTICSEARCH_HOST= "localhost"
      - ELASTICSEARCH_PORT= "9200"
    networks:
      - es-net
    depends_on:
      - elasticsearch
      - kibana
    volumes:
      - type: bind
        source: ./elastalert.yml
        target: /opt/elastalert/config.yaml
      - type: bind
        source: ./rules
        target: /opt/elastalert/rules
      - type: bind
        source: ./smtp_auth_file.yaml
        target: /opt/elastalert/smtp_auth_file.yaml
networks:
  es-net:
    driver: bridge
